# Generated by Django 5.2.7 on 2025-11-04 09:22

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecordingSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('failed', 'Failed'), ('processing', 'Processing')], default='active', max_length=20)),
                ('total_chunks', models.IntegerField(default=0)),
                ('total_duration', models.FloatField(default=0.0, help_text='Duration in seconds')),
                ('audio_file', models.CharField(blank=True, max_length=500, null=True)),
                ('file_size', models.BigIntegerField(default=0, help_text='File size in bytes')),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('processing_started_at', models.DateTimeField(blank=True, null=True)),
                ('processing_completed_at', models.DateTimeField(blank=True, null=True)),
                ('processing_error', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'recording_sessions',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['-started_at'], name='recording_s_started_88ce88_idx'), models.Index(fields=['status'], name='recording_s_status_b4c958_idx')],
            },
        ),
        migrations.CreateModel(
            name='Transcript',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_text', models.TextField()),
                ('language', models.CharField(default='ru', max_length=10)),
                ('total_speakers', models.IntegerField(default=0)),
                ('total_utterances', models.IntegerField(default=0)),
                ('confidence_avg', models.FloatField(default=0.0, help_text='Average confidence score')),
                ('whisper_model', models.CharField(default='medium', max_length=50)),
                ('diarization_model', models.CharField(default='pyannote/speaker-diarization-3.1', max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transcript', to='recordings.recordingsession')),
            ],
            options={
                'db_table': 'transcripts',
            },
        ),
        migrations.CreateModel(
            name='Utterance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('speaker', models.CharField(max_length=50)),
                ('text', models.TextField()),
                ('start_time', models.FloatField()),
                ('end_time', models.FloatField()),
                ('confidence', models.FloatField(default=0.0)),
                ('sequence_number', models.IntegerField()),
                ('transcript', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utterances', to='recordings.transcript')),
            ],
            options={
                'db_table': 'utterances',
                'ordering': ['sequence_number'],
            },
        ),
        migrations.CreateModel(
            name='AudioChunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chunk_number', models.IntegerField()),
                ('chunk_size', models.IntegerField(help_text='Size in bytes')),
                ('file_path', models.CharField(max_length=500)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='recordings.recordingsession')),
            ],
            options={
                'db_table': 'audio_chunks',
                'ordering': ['chunk_number'],
                'indexes': [models.Index(fields=['session', 'chunk_number'], name='audio_chunk_session_e8c80b_idx')],
                'unique_together': {('session', 'chunk_number')},
            },
        ),
        migrations.AddIndex(
            model_name='transcript',
            index=models.Index(fields=['session'], name='transcripts_session_f11e1d_idx'),
        ),
        migrations.AddIndex(
            model_name='utterance',
            index=models.Index(fields=['transcript', 'sequence_number'], name='utterances_transcr_41fe59_idx'),
        ),
        migrations.AddIndex(
            model_name='utterance',
            index=models.Index(fields=['speaker'], name='utterances_speaker_21d278_idx'),
        ),
    ]
