# Generated by Django 5.2.7 on 2025-11-04 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recordings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='audiochunk',
            options={'ordering': ['chunk_number'], 'verbose_name': 'Чанк', 'verbose_name_plural': 'Чанки'},
        ),
        migrations.AlterModelOptions(
            name='recordingsession',
            options={'ordering': ['-started_at'], 'verbose_name': 'Сессия', 'verbose_name_plural': 'Сессии'},
        ),
        migrations.AlterModelOptions(
            name='transcript',
            options={'verbose_name': 'Транскрипт', 'verbose_name_plural': 'Транскрипты'},
        ),
        migrations.AlterModelOptions(
            name='utterance',
            options={'ordering': ['sequence_number'], 'verbose_name': 'Фраза', 'verbose_name_plural': 'Фразы'},
        ),
        migrations.RenameIndex(
            model_name='audiochunk',
            new_name='recordings__session_cdaa6b_idx',
            old_name='audio_chunk_session_e8c80b_idx',
        ),
        migrations.RenameIndex(
            model_name='recordingsession',
            new_name='recordings__started_51359c_idx',
            old_name='recording_s_started_88ce88_idx',
        ),
        migrations.RenameIndex(
            model_name='recordingsession',
            new_name='recordings__status_8e15d2_idx',
            old_name='recording_s_status_b4c958_idx',
        ),
        migrations.RenameIndex(
            model_name='transcript',
            new_name='recordings__session_8a6bb4_idx',
            old_name='transcripts_session_f11e1d_idx',
        ),
        migrations.RenameIndex(
            model_name='utterance',
            new_name='recordings__transcr_364bdc_idx',
            old_name='utterances_transcr_41fe59_idx',
        ),
        migrations.RenameIndex(
            model_name='utterance',
            new_name='recordings__speaker_05a25a_idx',
            old_name='utterances_speaker_21d278_idx',
        ),
        migrations.AlterModelTable(
            name='audiochunk',
            table=None,
        ),
        migrations.AlterModelTable(
            name='recordingsession',
            table=None,
        ),
        migrations.AlterModelTable(
            name='transcript',
            table=None,
        ),
        migrations.AlterModelTable(
            name='utterance',
            table=None,
        ),
    ]
