# Generated by Django 5.2.7 on 2025-11-04 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordings', '0002_alter_audiochunk_options_and_more'),
    ]

    operations = [
        # Переименовываем модель RecordingSession в Session
        migrations.RenameModel(
            old_name='RecordingSession',
            new_name='Session',
        ),
        # Добавляем новые поля для информации о вкладке браузера
        migrations.AddField(
            model_name='session',
            name='tab_url',
            field=models.URLField(blank=True, help_text='URL вкладки откуда была запись', max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='tab_title',
            field=models.CharField(blank=True, help_text='Заголовок вкладки', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='tab_favicon',
            field=models.URLField(blank=True, help_text='URL иконки сайта', max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='browser_info',
            field=models.JSONField(blank=True, help_text='Дополнительная информация о браузере', null=True),
        ),
    ]
